[package]
name = "bus-passenger-number-5648b12ce68d9daa6b000099"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
